[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "manual-master"
version = "0.1.0"
dependencies = [
    "langchain",
    "langchain-chroma",
    "langchain-community",
    "langchain-openai",
    "python-magic; sys.platform != \"win32\"",
    "python-magic-bin==0.4.14; sys.platform == \"win32\"",
]

[project.scripts]
manual-master = "manual-master.__main__:main"
